defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

cache_key: &cache_key
  key: dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache: 
          <<: *cache_key
      - run:
          name: install dependencies with npm
          command: npm install
      - run: npm test
      - save_cache:
          <<: *cache_key
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
