version: 2.1

alias:
  - &cache_key
    key: dependency-cache-node-14-{{ checksum "package.json" }}
  - &dir ~/repo
  - &attach_workspace
    attach_workspace:
          at: *dir


executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: install dependencies with npm
          command: npm install
      - save_cache:
          <<: *cache_key
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *dir
          paths:
            - .

  test:
    executor: default
    steps:
      - *attach_workspace
      - run: npm test

  release:
    executor: default
    steps:
      - *attach_workspace
      - checkout
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
